name: Mirror to GitLab
on:
  push:
    branches: ["**"]
  delete: {}
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push mirror to GitLab
        env:
          GL_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git push --prune "https://oauth2:${GL_TOKEN}@gitlab.com/hwillGIT/visual-essay-generator.git" "+refs/remotes/origin/*:refs/heads/*" "+refs/tags/*:refs/tags/*"
